### ISSUE TITLE
pywebio_battery login persistent wrong localstorage

### ISSUE THREAD

**Issue by XuanShine** [pywebio/pywebio-battery#1]
BUG Description

The function login in pywebio_battery has a wrong localstorage:

Once logged in, the function: set_localstorage("token", signed)
But when it wants to check if logged in: get_localstorage("webio-token")

**Comment by wang0618** [comment]
Oops, forgot to update this issue.  This issue was already resolved. A new parameter `token_name` is added to indicate the key name to store the auth info in localstorage.

See: https://pywebio.readthedocs.io/en/latest/battery.html#pywebio_battery.basic_auth
