### ISSUE TITLE
在Windows简中系统里使用pywebio_battery.run_shell会报错

### ISSUE THREAD

**Issue by LawrenceDon** [pywebio/pywebio-battery#2]
https://github.com/pywebio/pywebio-battery/blob/f62815b8de8577df34b76e919841708924eb24dd/pywebio_battery/interaction.py#L117

在Windows简中系统里使用pywebio_battery.run_shell会报错：
>  File "xxxxxx\venv\lib\site-packages\pywebio_battery\interaction.py", line 93, in run_shell
>     output_func(out.decode('utf8'))
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 1: invalid continuation byte

需要将pywebio_battery/interaction.py#L117的output_func(out.decode('utf8')) 改为 output_func(out)
然后下面的代码就可以正常运行了
```
def myFunc(input):
    put_text(input.decode('GBK'))

def main():
    pywebio_battery.run_shell('dir',output_func=myFunc)
```

**Comment by wang0618** [comment]
抱歉忘记更新这个issue了，`run_shell()` 里后来添加了一个 `encoding` 参数可以用来设置shell输出的编码
