### ISSUE TITLE
popup_input cancel but return result dict

### ISSUE THREAD

**Issue by OliverQing** [pywebio/pywebio-battery#3]
Hey， I'm Oliver. 

Want to drop a bug issue. 

Case: 
 use pop_input to create widget. I set the validate function and cancelable is True. 
 On the page,  If I submit once but banned by the validate function and click cancel. The cancel will return value dict instead of None.
The code bellows might help to reproduce this situation.
 `
my_list = ['1']
def insert_value_to_list():
    def validate(res):
       if res['value'] in my_list:
           raise "value","value exist in list"
    form_result = popup_input('list value'
        [
            put_input('value')
        ] ,cacelable=True,validate=validate
                        )
print(form)
`
input "1" and submit then cancel.

**Comment by OliverQing** [comment]
Sorry for the bad code format...

**Comment by wang0618** [comment]
It has been fixed in pywebio v1.8.3, see https://github.com/pywebio/PyWebIO/issues/614

**Comment by wang0618** [comment]
It's a bug of pywebio-battery, I will fix later

**Comment by OliverQing** [comment]
Great!  Thank you for your quick feedback.

**Comment by OliverQing** [comment]
oops. ok , thanks.

**Comment by wang0618** [comment]
fixed in pywebio-battery v0.5.1
